### ISSUE TITLE
Enhancement: Generate QR Code For Invite Link 

### ISSUE THREAD

**Issue by recursivecodes** [aws-samples/amazon-ivs-real-time-basic-web-demo#2]
It would be awesome if the app could generate a QR code and display it in a dialog when clicking the 'Copy Invite Link' button. This would make it very easy to demo this application during a presentation or workshop so that a guest can scan the code and quickly join the session.

**Comment by slee-aws** [comment]
@recursivecodes - I've implemented a basic version of this in the following branch: https://github.com/aws-samples/amazon-ivs-real-time-basic-web-demo/pull/4.

Please check out the branch and let me know if it works for you use-case. Thanks!

**Comment by slee-aws** [comment]
Merged #4
